config/routes.rb
Meerkat::Application.routes.draw do

  get "statements/create"

  get "statements/destroy"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :statements, only: [:create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/profile', to: 'users#show'

  match '/signin', to: 'sessions#new' 
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match '/account', to: 'static_pages#account'

  match '/new', to: 'statements#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

#This is our USER MODEL - People's information will be stored here.

class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation
  has_secure_password
  has_many :statements, dependent: :destroy

  before_save { |user| user.email=email.downcase}
  before_save :create_remember_token

  self.per_page = 10

#Validations
	
	VALID_USERNAME_REGEX = /\A[\w+\-.]+\z/i
  validates :username, presence: true, length: {maximum: 15}, format: {with: VALID_USERNAME_REGEX}, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
# ----------------------------------------------------- This controls the page for signing up 
# ----------------------------------------------------- (creating a new user in the USER MODEL (user.rb))



class UsersController < ApplicationController
before_filter :signed_in_user, only: [:index, :edit, :update, :delete]
before_filter :correct_user,   only: [:edit, :update, :show]
before_filter :admin_user,     only: :destroy
# before_filter :not_signed_in_user, only: :new

	def show
# ----------------------------------------------------- Defining the @user variable for the show page!
    @user= User.find(params[:id])
    @satements = @user.statements.paginate page: params[:page]
	end




  def new
# ----------------------------------------------------- Defining the @user variable for the form at new.html.erb
  	@user= User.new
	end



# ----------------------------------------------------- This part controls what happens when creating a new user 
# ----------------------------------------------------- using the Sign Up form (First part is success, second is failed)
	def create
	   @user = User.new(params[:user])
	   if @user.save
	   	sign_in @user
	   	flash[:success] = "Welcome to Katmeer!"
	   	redirect_to root_path
	   else
	     render 'new'
	    end
	end



# ----------------------------------------------------- These are the edit pages.
  def edit
#    @user = User.find(params[:id])
#	  case params[:form]
#		  when "email"
#		    render 'email'
#		  when "password"
#		    render 'password'
#		  else
#		    render :action => :edit
#	  end
	end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end



# ----------------------------------------------------- This is the index page.
  def index
    @users = User.paginate page: params[:page],
                            :order => 'username'
    respond_to do |format|
      format.html
      format.js # add this line for your js template
    end
  end
#    @users = User.order(:username).page params[:page]

# ----------------------------------------------------- This is for deleting users.
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end


  private

# ----------------------------------------------------- Signed_in_user for authorization.
    def not_signed_in_user
      if signed_in?
        redirect_to current_user
      end
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/_user.html.haml
%li
	= gravatar_for user
	= link_to user.username, user
	-if current_user.admin? && !current_user?(user)
		|
		= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.haml
-provide(:title, 'Update Your Profile')

.row
	.small-8.large-6.small-centered.columns
		= form_for(@user) do |f|
			%p
				Change Your Email
			= render 'shared/error_messages', object: f.object
			= f.label :email
			= f.text_field :email
			= f.label :password
			= f.password_field :password
			= f.label :password_confirmation
			= f.password_field :password_confirmation
			= f.submit "Save Changes", class: "button"

app/views/users/email.html.haml
-provide(:title, 'Change Your Email')

.row
	.small-8.large-6.small-centered.columns
		= form_for(@user, form: "email") do |f|
			%h1
				Change Your Email
			= f.label :email
			= f.text_field :email
			= f.submit "Save Changes", class: "button"

app/views/users/index.html.haml
- provide(:title, 'All Kats')
%h1 All Kats

%ul.users
	=render @users

= will_paginate @users

//= link_to 'Load More Users', users_path(:page => @users.next_page), :class => 'load-more-posts', :remote => true if @users.next_page

app/views/users/index.js.haml
$('.users').append('#{escape_javascript(render @users)}');
$('a.load-more-users').attr('href', '#{users_path page: @users.next_page}');
 
- unless @users.next_page
	$('a.load-more-users').remove();

app/views/users/new.html.erb
<% provide(:title,'Sign Up')%>

<h1>Sign Up Here!</h1>

<div id= "form" class= "row">
	<div class= "small-6 small-centered columns">
		<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
			<%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :username %>
      <%= f.text_field :username %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Sign Up", class: "button small-centered columns submitButton" %>
    <% end %>
    <p> Already have an account? <%= link_to 'Sign in!', signin_path %>
  </div>
</div>

app/views/users/show.html.haml
- provide(:title, @user.username)

.row
	%h1.username
		#{@user.username} | Dashboard
	#side.panel.small-4.columns
		.gravatar
			= gravatar_for @user
		%p
			%div
				Email: #{@user.email} #{ link_to 'edit', edit_user_path(@user)}
			%div
				Password: *hidden* #{ link_to 'edit', edit_user_path(@user)}
			%div
				%a{href: "http://gravatar.com/emails"} Change
				your gravatar.
	.small-8.columns
		- if @user.statements.any?
			%h1 Things You're Following
			%ol.statements
				= render @statements
				= will_paginate @statements
		- else
			%h2 You're not following anything!