config/routes.rb
Meerkat::Application.routes.draw do

  get "statements/create"

  get "statements/destroy"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :statements, only: [:create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/profile', to: 'users#show'

  match '/signin', to: 'sessions#new' 
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match '/account', to: 'static_pages#account'

  match '/new', to: 'statements#new'

end

app/views/layouts/_nav.html.haml
/This is the navigation partial

%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        %a{href: "/"} Katmeer

    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu

  %section.top-bar-section
    %ul.left
      %li.divider
      %li
      %li
        =link_to "Browse", '#'
    %ul.right
      - if signed_in?
        %li.has-dropdown
          =link_to current_user.username, current_user
          %ul.dropdown
            %li.divider
            %li
              =link_to 'Account', current_user
            %li
              = link_to 'Sign Out', signout_path, method: "delete"
      - else
        %li
          = link_to 'Sign Up', signup_path
        %li
          = link_to 'Sign In', signin_path

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!

%html{:lang => "en"}
  / <![endif]

  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag  "application"
    = stylesheet_link_tag  "custom"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags


  / |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||


  %body
    .stick
      = render 'layouts/nav'
    .flash
      - flash.each do |key, value|
        %div{:class => "alert-box alert-#{key}"}= value
    .container.row
      .small-10.small-centered.columns.wrapper
        = yield
        = javascript_include_tag "application"
        = debug(params) if Rails.env.development?